<?php
/**
 * @file
 * Code for the GSB Feature Alumni Reunion Agenda Item Display feature.
 */

include_once 'gsb_feature_alumni_reunion_agenda_item_display.features.inc';

/**
 * Implementation of hook_views_query_alter
 * @param type $view
 * @param type $query
 */
function gsb_feature_alumni_reunion_agenda_item_display_views_query_alter(&$view, &$query) {
  if ($view->name == 'gsb_alumni_agenda_list') {
    unset($view->query->where[0]);
    $node = node_load($view->args[0]);
    if (!empty($node->field_reunion_session_ref)) {
      $view->query->where[1]['conditions'][2]['value'] = $node->field_reunion_session_ref[$node->language][0]['target_id'];
      $view->query->where[2]['conditions'][0]['value'] = $view->args[0];
    }
  }
}
